# Generated by Django 6.0.1 on 2026-01-30 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('PERFECT', '完遂'), ('GOOD', '5割'), ('FAILED', '失敗')], default='FAILED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.CharField(max_length=20)),
                ('time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('level', models.CharField(choices=[('STORONG', '強'), ('MIDIUN', '中'), ('SOFT', '弱'), ('CUSTOM', 'カスタム')], default='MIDIUN', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
