# Generated by Django 6.0.1 on 2026-01-30 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_custom', models.BooleanField(default=True)),
                ('menu', models.TextField(max_length=200)),
                ('strength', models.CharField(choices=[('-', '-'), ('weak', '弱'), ('normal', '中'), ('strong', '強')], default='-', max_length=20)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
