# Generated by Django 6.0.1 on 2026-01-30 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setmenu',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='setmenu',
            name='make_custom',
        ),
        migrations.RemoveField(
            model_name='setmenu',
            name='user',
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='menu',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='starttime',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='setmenu',
            name='weekday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='custom.weekday'),
            preserve_default=False,
        ),
    ]
