# Generated by Django 6.0.1 on 2026-01-31 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_alter_setmenu_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmenu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
