# Generated by Django 6.0.1 on 2026-01-31 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_setmenu_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setmenu',
            old_name='strength',
            new_name='level',
        ),
    ]
